name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# https://github.com/marketplace/actions/docker-layer-caching
jobs:
  build-start-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run:  |
          cp .env.example .env
          make build

      - name: Run Unit Tests
        run:  make test